import { put } from '@vercel/blob';
import { getDb, initDb, getDatabaseUrl } from './db.js';

export const config = {
  api: {
    bodyParser: false,
  },
};

export function getBlobToken() {
  if (process.env.BLOB_READ_WRITE_TOKEN) return process.env.BLOB_READ_WRITE_TOKEN;

  // Scan for any token generated by custom-named Blob stores (e.g., NAVKAR_PHOTOGRAPHY_BLOB_READ_WRITE_TOKEN)
  for (const key of Object.keys(process.env)) {
    if (key.includes('BLOB') && key.includes('TOKEN') && process.env[key]) {
      return process.env[key];
    }
  }
  for (const key of Object.keys(process.env)) {
    if (key.endsWith('READ_WRITE_TOKEN') && process.env[key]) {
      return process.env[key];
    }
  }
  return null;
}

export default async function handler(req, res) {
  // CORS Headers
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, x-filename'
  );

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const blobToken = getBlobToken();
  if (!blobToken) {
    return res.status(500).json({
      error: 'Vercel Blob Storage token not detected. Please verify your Blob Store in Vercel > Storage and redeploy.'
    });
  }

  const dbUrl = getDatabaseUrl();
  if (!dbUrl) {
    return res.status(500).json({
      error: 'Database connection URL not detected. Please verify Neon in Vercel > Storage and redeploy.'
    });
  }

  const { bucket, filename } = req.query;
  const rawFileName = filename || req.headers['x-filename'] || `file-${Date.now()}.jpg`;

  if (!bucket) {
    return res.status(400).json({ error: 'Bucket parameter is required' });
  }

  try {
    // Read request body stream into Buffer
    const chunks = [];
    for await (const chunk of req) {
      chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
    }
    const buffer = Buffer.concat(chunks);

    if (buffer.length === 0) {
      return res.status(400).json({ error: 'Uploaded file is empty' });
    }

    const safeFilename = rawFileName.replace(/[^a-zA-Z0-9._-]/g, '_');
    const uniquePath = `${bucket}/${Date.now()}-${safeFilename}`;

    // Upload directly to Vercel Blob Storage with discovered token
    const blob = await put(uniquePath, buffer, {
      access: 'public',
      token: blobToken,
      contentType: req.headers['content-type'] || 'image/jpeg',
    });

    // Save record to Neon PostgreSQL
    const sql = getDb();
    await initDb();

    const inserted = await sql`
      INSERT INTO gallery_images (bucket, name, url)
      VALUES (${bucket}, ${uniquePath}, ${blob.url})
      RETURNING id, bucket, name, url, created_at;
    `;

    return res.status(200).json({
      name: uniquePath,
      url: blob.url,
      bucket: bucket,
      dbRecord: inserted[0]
    });
  } catch (error) {
    console.error('Upload handler error:', error);
    return res.status(500).json({ error: error.message || 'Upload failed' });
  }
}
